events/urls.py
from django.conf.urls import url
from .views import (
    EventList, EventDetail, create_event, EventDelete, update_event, join_event
)

urlpatterns = [
    url(r'^$', EventList.as_view(), name='EventList'),
    url(r'^(?P<pk>[\d]+)/$', EventDetail.as_view(), name='EventDetail'),
    url(r'^(?P<pk>[\d]+)/delete/$', EventDelete.as_view(), name='EventDelete'),
    url(r'^(?P<pk>[\d]+)/update/$', update_event, name='EventUpdate'),
    url(r'^create/$', create_event, name='EventCreate'),
    url(r'^(?P<pk>[\d]+)/join/$', join_event, name='EventJoin'),
]

magazine/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from .views import home_page, privacy

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page, name='homepage'),
    url(r'^privacy$', privacy, name='privacy'),
    url(r'^account/', include('allauth.urls')),
    url(r'^account/', include('accounts.urls', namespace='account')),
    url(r'^articles/', include('articles.urls', namespace='articles')),
    url(r'^events/', include('events.urls', namespace='events')),
    url(r'^places/', include('places.urls', namespace='places')),
    url(r'^travels/', include('travels.urls', namespace='travels')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

places/urls.py
from django.conf.urls import url
from .views import (
    PlaceList, PlaceDetail, create_place, PlaceDelete, update_place
)

urlpatterns = [
    url(r'^$', PlaceList.as_view(), name='PlaceList'),
    url(r'^(?P<pk>[\d]+)/$', PlaceDetail.as_view(), name='PlaceDetail'),
    url(r'^(?P<pk>[\d]+)/delete/$', PlaceDelete.as_view(), name='PlaceDelete'),
    url(r'^(?P<pk>[\d]+)/update/$', update_place, name='PlaceUpdate'),
    url(r'^create/$', create_place, name='PlaceCreate'),
]

events/models.py
from django.db import models
from places.models import Place
from accounts.models import User
from multimedia.models import Image, Video

from common.miscellaneous import get_file_path
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.fields import GenericRelation
from ckeditor.fields import RichTextField
from django.conf import settings
import stripe


# Create your models here.
class Event(models.Model):
    users = models.ManyToManyField(User, related_name='events', blank=True)
    location = models.ForeignKey(Place, related_name='events')
    title = models.CharField(_('title'), max_length=255)
    description = RichTextField(max_length=2048)
    start = models.DateTimeField(db_index=True)
    end = models.DateTimeField(db_index=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, db_index=True, blank=True, null=True)
    limit = models.PositiveIntegerField()
    available_seats = models.PositiveSmallIntegerField(blank=True)
    cover_img = models.ImageField(upload_to=get_file_path(file_dir='events-cover-imgs/'))
    images = GenericRelation(Image, related_query_name='events')
    videos = GenericRelation(Video, related_query_name='events')
    created = models.DateTimeField(_('Time Created'), auto_now_add=True)  # add current date.

    class Meta:
        index_together = ['start', 'end']
        ordering = ['start']

    def __str__(self):
        return self.title

    @property
    def duration(self):
        if (self.end - self.start).days <= 1:
            return 1
        return (self.end - self.start).days

    @property
    def price_in_cents(self):
        if self.price:
            return int(str(self.price).replace('.', ''))
        pass

    # @property
    # def api_key(self):
    #     return settings.STRIPE_PUBLIC_KEY

    @classmethod
    def get_upcoming_events(cls, start, end):
        return cls.objects.filter(start__date__gte=start, end__date__lte=end).order_by('start')

    def charge(self, token, description, user, currency='usd', tickets=1, capture=True):
        """
        charges the user, add him to the event and create event reservation if the event have a price.
        :param token: Str
        :param description: Str
        :param user: User object
        :param currency: Str
        :param tickets: Integer
        :param capture: Boolean
        :return: Boolean
        """
        if capture:
            stripe.api_key = settings.STRIPE_SECRET_KEY
            try:
                charge = stripe.Charge.create(
                    amount=self.price_in_cents * tickets, currency=currency, source=token, description=description
                )
                reservation = self.reservations.create(
                    user=user, event=self, tickets=tickets, charge_id=charge['id'], paid=True
                )
                self.available_seats -= tickets
                return reservation
            except stripe.error.CardError as e:
                print('there was an error charging the user.', e)
                print('error == ', e is True)
                return False
        else:
            try:
                charge = stripe.Charge.create(
                    amount=self.price_in_cents * tickets, currency=currency, source=token, description=description,
                    capture=False
                )
                reservation = self.reservations.create(
                    user=user, event=self, tickets=tickets, charge_id=charge['id']
                )
                self.available_seats -= tickets
                return reservation
            except stripe.error.CardError as e:
                print('there was an error charging the user.')
                return False

events/forms.py
from django import forms
from .models import Event


class CreateEventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['title', 'description', 'location', 'start', 'end', 'limit', 'price']

events/views.py
from datetime import datetime
from django.contrib import messages
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, DeleteView
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator
from django.core.cache import caches
from django.conf import settings

from .models import Event
from accounts.models import User

from .forms import CreateEventForm
from multimedia.forms import CreateImageForm, CreateVideoForm
from multimedia.utils import create_image, create_video

db_cache = caches['db']


# Create your views here.
class EventList(ListView):
    model = Event
    queryset = Event.objects.filter(start__date__gte=datetime.now().date())
    template_name = 'events/list_events.html'
    context_object_name = 'events'

    def get_context_data(self, **kwargs):
        context = super(EventList, self).get_context_data(**kwargs)
        context.update({
            'popular_authors': db_cache.get('popular_authors'),
            'popular_articles': db_cache.get('popular_articles'),
            'popular_events': db_cache.get('popular_events'),
            'api_key': settings.STRIPE_PUBLIC_KEY,
        })
        return context


class EventDetail(DetailView):
    model = Event
    template_name = 'events/detail_event.html'
    context_object_name = 'event'

    def get_context_data(self, **kwargs):
        context = super(EventDetail, self).get_context_data(**kwargs)
        context.update({
            'popular_authors': db_cache.get('popular_authors'),
            'popular_articles': db_cache.get('popular_articles'),
            'popular_events': db_cache.get('popular_events')
        })
        return context


@method_decorator(user_passes_test(lambda u: u.is_superuser or u.is_staff), name='dispatch')
class EventDelete(LoginRequiredMixin, DeleteView):
    model = Event
    success_url = reverse_lazy('events:EventList')


@login_required()
@user_passes_test(lambda u: u.is_superuser or u.is_staff)
def create_event(request):
    form1 = CreateEventForm(request.POST or None)
    form2 = CreateImageForm(request.POST or None, request.FILES or None)
    form3 = CreateVideoForm(request.POST or None, request.FILES or None)
    if form1.is_valid() and form2.is_valid() and form3.is_valid():
        event = form1.save(commit=False)
        event.user = User.objects.get(pk=request.user.pk)
        event.save()
        for img in request.FILES.getlist('image'):
            create_image(img=img, target=event, target_img_name='events/imgs/')
        for vid in request.FILES.getlist('video'):
            create_video(vid=vid, target=event, target_vid_name='events/vids/')
        return HttpResponseRedirect("/events/{event.pk}/update/")
    return render(request, 'events/create_event.html',
                  {'form1': form1, 'form2': form2, 'form3': form3})


@login_required()
@user_passes_test(lambda u: u.is_superuser or u.is_staff)
def update_event(request, pk):
    event = get_object_or_404(Event, id=pk)
    form = CreateEventForm(request.POST or None, instance=event)
    # vid_form = CreateVideoForm(request.POST or None, request.FILES or None)
    if form.is_valid(): # vid_form.is_valid()
        if form.has_changed():
            form.save()
            return HttpResponseRedirect("/events/{pk}/update")
        # print(form1.errors, form2.errors)
    return render(request, 'events/update_event.html',
                  {'form': form})


@login_required()
def join_event(request, pk):
    print('is this view even work?')
    event = get_object_or_404(Event, id=pk)
    has_reservation = event.reservations.filter(user=request.user, event=event).exists()
    tickets = int(request.POST.get('tickets', 1))
    if not event.price and not has_reservation:
        event.users.add(request.user)
        event.reservations.create(user=request.user, event=event, tickets=tickets)
        event.available_seats -= tickets
        event.save()
        print('done join free')
        messages.success(request, 'you have successfully joined the event.', extra_tags='success')
    elif event.price and not has_reservation:
        description = "reserved {tickets} tickets for {request.user.username}."
        charged = event.charge(request.data['stripeToken'], description, request.user, tickets=tickets)
        print('before charged check')
        if charged:
            event.users.add(request.user)
            event.available_seats -= tickets
            event.save()
            print('done join non free')
            messages.success(request, 'you have successfully joined the event.', extra_tags='success')
        messages.error(request, 'error while charging the user, please try again.', extra_tags='alert')
    elif has_reservation:
        print('already have reservation.')
        messages.warning(request, 'action not permitted, you already made a reservation.', extra_tags='warning')
        return EventList.as_view()(request)
    return render(request, 'events/detail_event.html', {'event': event})


# if img_form.has_changed():
#     img_form.changed_data
#     for img in request.FILES.getlist('image'):
#         update_image(img=img, target=event, target_img_name='events/imgs/')
# if vid_form.has_changed():
#     for vid in request.FILES.getlist('video'):
#         create_video(vid=vid, target=event, target_vid_name='events/vids/')

events/templates/events/create_event.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Create Event{% endblock %}
{% block content %}
    <div class="forms">
        {% for error in form.errors %}<div class="cell small-12">{{ error }}</div>{% endfor %}
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form1.as_p }}
            {{ form2.as_p }}
            {{ form3.as_p }}
            <button class="button" type="submit">Save</button>
        </form>
    </div>
{% endblock %}
{% block right_sidebar %}{% endblock %}
{% block scripts %}
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
    {{ block.super }}
{% endblock %}

events/templates/events/detail_event.html
{% extends 'home/base.html' %}
{% block title %}{{ event.title|truncatewords:12 }} | Event{% endblock %}
{% block content %}
    <div class="event-page">
        <div class="grid-x grid-padding-x">
            <div class="cell small-12">
                <div class="rec-box" style="background: url('{{event.images.first.image.url}}') no-repeat center center;
                        background-size: cover;">
                </div>
                <div class="caption">
                    <h4 class="">{{ event.title }}</h4>
                    <p class="">
                        {{ event.description|safe }}
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

events/templates/events/event_confirm_delete.html
{% extends 'home/base.html' %}
{% block title %}Confirm Deleting Event{% endblock %}
{% block content %}
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" />
    </form>
{% endblock %}

events/templates/events/list_events.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Events{% endblock %}
{% block content %}
<div class="events-page">
    <div class="grid-x grid-margin-x grid-padding-x">
        {% for event in events %}
        <div class="cell small-12 medium-12">
            <div class="event grid-x">
                <div class="event-header small-12 grid-x grid-padding-x   ">
                    <div class="cell small-2  text-center">
                        <div class="day-month">
                            <div class="month">{{ event.start|date:'M' }}</div>
                            <div class="day">{{ event.start|date:'j' }}</div>
                        </div>
                    </div>
                    <div class="cell small-7 event-details">
                        <div class="cell small-12 event-details">
                            <h5>
                                <a href="{% url 'events:EventDetail' event.pk %}">{{ event.title|truncatechars:40 }}</a>
                            </h5>
                        </div>
                        <p class="event-duration">From:
                            <i class="fa fa-calendar"></i> {{ event.start|date:'M. j, o, h:i A' }} <br>
                            To: <i class="fa fa-calendar"></i>  {{ event.end|date:'M. j, o, h:i A' }}</p>
                        <p class="event-address">
                            <a href="{% url 'places:PlaceDetail' event.location.pk %}" style="color: #000;">
                                <i class="fa fa-map-marker"></i> &nbsp;{{ event.location.location }}
                            </a>
                        </p>

                    </div>
                    <div class="cell small-3">
                        <p class="event-price text-center">
                            {% if event.price %}
                                ${{ event.price }}
                            {% else %}
                                Free
                            {% endif %}
                            <br><span style="font-size: 0.9rem;">available seats: {{ event.available_seats }}</span>
                        </p>
                        <a href="#" class="button rsvp-button" data-open="joinEventModal{{ forloop.counter0 }}">RSVP</a>
                        <div id="joinEventModal{{ forloop.counter0 }}" data-reveal class="reveal joinEventModals">
                            <h4>please specify the number of tickets.</h4>
                            <label for="tickets">Tickets: </label>
                            <input type="number" name="tickets" value="1" min="1" max="{{ event.limit }}" class="input tickets">
                            {% if event.price %}
                            <button class="button rsvp-button-pay" type="button" data-price="{{ event.price_in_cents }}"
                                    data-url="{% url 'events:EventJoin' event.pk %}" >RSVP</button>
                            {% else %}
                            <button class="button rsvp-button-finish" data-url="{% url 'events:EventJoin' event.pk %}"
                                    type="button">RSVP</button>
                            {% endif %}

                            <button class="close-button" data-close aria-label="Close modal" type="button">
                                <span aria-hidden="true">&times;</span>
                            </button>
{#                        <form action="{% url 'events:EventJoin' event.pk %}" method="post">#}
{#                        {% if event.price %}#}
{#                          <script#}
{#                            src="https://checkout.stripe.com/checkout.js" class="stripe-button"#}
{#                            data-key="{{ api_key }}"#}
{#                            data-amount="{{ event.price_in_cents }}"#}
{#                            data-name="Gemspedia"#}
{#                            data-description="charge for {{ event.title|truncatechars:20 }} Event"#}
{#                            data-image="{% static 'images/logo1.png' %}" {#https://stripe.com/img/documentation/checkout/marketplace.png#}
{#                            data-locale="auto">#}
{#                          </script>#}
{#                        {% endif %}#}
{#                        </form>#}
                        </div>
                    </div>
                </div>
                <div class="cell small-11 small-offset-1 ">
                    <p class="event-description">{{ event.description|safe|truncatewords:30 }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}
{% block scripts %}
    <script src="https://checkout.stripe.com/checkout.js"></script>
    {{ block.super }}
    <script>
    jQuery(document).ready(function($){
        var csrf = $("{% csrf_token %}").val();
        var handler = StripeCheckout.configure({
          key: '{{ api_key }}',
          image: '{% static 'images/logo1.png' %}',
          locale: 'auto',
          token: function(token) {
              var data = {
                  'csrfmiddlewaretoken': csrf, 'stripeToken': token.id, 'tickets': tickets
              }
              $.post({
                  url: url, data: data,
              });
          }
        });
        $('.joinEventModals').each(function(){
            $(this).on('open.zf.reveal', function() {
                $('.rsvp-button-pay', this).click(function(e) {
                    {#var tickets = $('.tickets', this).val();#}
                    {#var url = $(this).data('url');#}
                    var price = $(this).data('price');
                    handler.open({
                        name: 'Gemspedia',
                        description: 'Example Charge',
                        amount: price,
                    });
                    e.preventDefault();
                });
                $('.rsvp-button-finish', this).click(function(e) {
                    var tickets = $('.tickets', this).val();
                    var url = $(this).data('url');
                    $.post(url, {'csrfmiddlewaretoken': csrf, 'tickets': tickets});
                    e.preventDefault();
                });
            });
        });
        window.addEventListener('popstate', function() {
            handler.close();
        });
    });
    </script>
{% endblock %}

events/templates/events/update_event.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}Edit Event{% endblock %}
{% block content %}
    <div class="forms">
        {% for error in form.errors %}<div class="cell small-12">{{ error }}</div>{% endfor %}
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <button class="button" type="submit">Save</button>
        </form>
    </div>
{% endblock %}
{% block right_sidebar %}{% endblock %}
{% block scripts %}
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
    {{ block.super }}
{% endblock %}